--- # Criação do serviço para conta do usuário
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-admin-root
  namespace: default

--- #Definindo a regra de acesso do usuário: kubernetes-admin
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-admin-root
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-admin-root
  namespace: default